file_path:
  features_file: "data/2_OTU/GDMicro_T2D_features.csv"
  labels_file: "data/2_OTU/GDMicro_T2D_labels.csv"
  distance_matrix_output: "data/3_distance_matrix/GDMicro_T2D.csv"
  adj_matrix_output: "data/4_adj_matrix/GDMicro_T2D.csv"

data:
  is_balanced: False
  dissimilarity_measure: "EUCLIDEAN"
  val_test_ratio: 0.3

model:
  perc_val: 25
  is_balanced: false
  num_classes: 2
  num_layers: 3
  num_sample1: 90
  num_sample2: 15
  embed_dim: 32
  lr: 0.005
  epoch: 50
