file_path:
  features_file: "data/2_OTU/GDMicro_T2D_features.csv"
  labels_file: "data/2_OTU/GDMicro_T2D_labels.csv"
  distance_matrix_output: "data/3_distance_matrix/GDMicro_T2D.csv"
  adj_matrix_output: "data/4_adj_matrix/GDMicro_T2D.csv"

data:
  is_balanced: False
  dissimilarity_measure: "EUCLIDEAN" # MANHATTAN
  val_test_ratio: 0.3

model:
  perc_val: 15 # 40
  is_balanced: false
  num_classes: 2
  num_layers: 5
  embed_dim: 128
  lr: 0.001
  epoch: 70
  base_estimators: 10
